spring:
  application:
    name: MushinChoirProject


  datasource:
    url : ${DATASOURCE_URL}
    password : ${DATASOURCE_PASSWORD}
    username: ${DATASOURCE_USER}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: mcmanuel755@gmail.com
    password: xoraowjcyvjwyaph
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  logging:
    level:
      org:
        springframework:
          security: TRACE

lombok:
  annotation:
    processing:
      enabled=true:

frontend:
  url : ${FRONTEND_URL}
